# Generated by Django 3.1.5 on 2021-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=150)),
                ('user_password', models.CharField(max_length=10)),
            ],
        ),
    ]
